name: clock_app
description: An alarm, clock, timer and stowatch app.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.3.4+12

environment:
  sdk: ">=2.18.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_boot_receiver: ^1.0.0
  # flutter_boot_receiver:
  #   path: "../flutter_boot_receiver"
  intl: ^0.19.0
  timezone: ^0.9.1
  timer_builder: ^2.0.0
  path_provider: ^2.0.11
  path: ^1.8.2
  sqflite: ^2.2.2
  flutter_slidable: ^3.1.0
  flutter_system_ringtones: ^0.0.6
  # android_alarm_manager_plus: ^4.0.1
  android_alarm_manager_plus:
    # path: "../plus_plugins/packages/android_alarm_manager_plus/"
    git:
      url: https://github.com/AhsanSarwar45/plus_plugins
      path: packages/android_alarm_manager_plus
      ref: alarm_show_intent
  just_audio: ^0.9.31
  awesome_notifications: ^0.9.3
  audio_session: ^0.1.13
  # flutter_windowmanager: ^0.2.0
  flutter_fgbg: ^0.3.0
  move_to_background: ^1.0.2
  vibration: ^1.7.6
  great_list_view:
    git:
      url: https://github.com/AhsanSarwar45/great_list_view
      ref: master
  get_storage: ^2.1.1
  queue: ^3.1.0+2
  table_calendar: ^3.0.8
  vector_math: ^2.1.4
  fuzzywuzzy: ^1.1.2
  flutter_show_when_locked: ^0.0.1
  # flex_color_picker:
  #   path: ../flex_color_picker
  flex_color_picker:
    git:
      url: https://github.com/vicolo-dev/flex_color_picker
      ref: master
  url_launcher: ^6.2.2
  flutter_html: ^3.0.0-beta.2
  http: ^0.13.6
  introduction_screen: ^3.1.12
  app_settings: ^5.1.1
  auto_start_flutter: ^0.1.1
  pick_or_save: ^2.2.4
  package_info_plus: ^6.0.0
  receive_intent: ^0.2.5
  watcher: ^1.1.0
  dynamic_color: ^1.7.0
  material_color_utilities: ^0.8.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  dart_code_metrics: ^5.5.1
  change_app_package_name: ^1.1.0
  dependency_validator: ^3.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/timezones.db
    - assets/images/
    - assets/ringtones/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-VariableFont.ttf
    - family: Rubik
      fonts:
        - asset: fonts/Rubik/Rubik-VariableFont.ttf

    - family: FluxIcons
      fonts:
        - asset: fonts/FluxIcons.ttf
